Shopify/mobile-buy-sdk-ios

README.md
Fix #9 
This points the Cocoapods shields.io badge to the new, public repo.
=> Pod spec badge: point to new, public repo

Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/GetShopOperation.h, Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/Info.plist, Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/ProductListViewController.m, Mobile Buy SDK.xcworkspace/xcshareddata/Mobile Buy SDK.xcscmblueprint, Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductView.h, Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductView.m, Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m, README.md
Fix #5 
This adds functionality for the `BUYProductViewController` to be pushed onto an existing navigation controller stack. Previously, there were some UI bugs associated with this presentation style. This has now been fixed.
I also took the chance to add it as a demo to the Advanced Sample App and snuck in a few comment fixes.
@davidmuzi Please review :eyes:
=> BUYProductViewController pushViewController: support

Mobile Buy SDK/Mobile Buy SDK/Models/BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYProduct.m
Fix #7 
This adds support for product tags. Tags are provided as a comma-separated string, but I have converted them to a NSSet so they're more useful for searching and filtering products locally.
=> Product tags

Mobile Buy SDK/Mobile Buy SDK/Product View/BUYNavigationController.m, Mobile Buy SDK/Mobile Buy SDK/Product View/Variant Selection/BUYOptionSelectionNavigationController.m
Fix #12 
This adds `appearanceWhenContainedInInstancesOfClasses:` and replaces calls on iOS 9 SDK for the deprecated `appearanceWhenContainedIn:`.
=> Update to appearanceWhenContainedInInstancesOfClasses:

README.md
*fixed to PR into `develop`*
BuildKite status badge now points to the new project on BK.
=> Update BuildKite badge

Mobile Buy SDK/Mobile Buy SDK/Models/BUYCart.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCart.m, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYImage.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYProductVariant.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYShop.h, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAdditions.h, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAdditions.m
This patch adds generics and nullability annotations to most obvious public APIs. (shopify/mobile-buy-sdk-ios#16)
There are several locations that it does not touch, such as model JSON deserialization and their respective properties. It would probably be best to make a design decision in terms of whether model properties should be considered optional or not and the deserialization system should take that into account.
=> Generics / Nullability Annotations

Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductView.m, Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m
*reopen as I opened against `master`*
Fix #27 
This adds logic that insets the product view's checkout button footer view if it's presented in a stack that includes a tab bar or a toolbar.
=> BUYProductViewController: Support for bottom inset when presented with tab bar and/or toolbar

Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.m
Fix #33
This adds a `note` to `BUYCheckout`, which will appear on the order in shop's admin.
It's not currently returned from the API, so not tests have been added.
=> Add note to BUYCheckout

Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.m, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYAddress+Additions.m, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayHelpers.m
Fix #36
Fix #37 
This fixes an issue with Apple Pay where, if the first address is not a valid shipping address for the shop and no shipping rates are returned, the rates are set to `nil` and it breaks validation on Shopify for all remaining calls to PATCH the `BUYCheckout` object, which would result in a continuous error callback on any subsequent - and valid - address selections.
=> Fix shipping rate issue for Apple Pay

Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAdditions.m, Mobile Buy SDK/Mobile Buy SDK/View Controllers/BUYViewController.m
- A discount with a cart that has multiple quantities of the same variant display the incorrect subtotal in the Apple Pay sheet. Note, this just displays the incorrect subtotal amount, the total and charged amount was correct.
- If an Apple Pay sheet is cancelled, the status appears as success, and we did not execute the code to release the reservations on the checkout
=> Apple Pay bug fixes

Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/CheckoutViewController.m
When using the "Checkout with Credit Card" option, and reviewing the order in Safari view, the checkout view was not dismissed when returning.
This implements the necessary delegate method to detect when the user is finished and reset to the collections view.
@davidmuzi @runmad
=> Pop to root after dismissing order status page

Mobile Buy SDK/docs/templates/html/document-template.html, Mobile Buy SDK/docs/templates/html/hierarchy-template.html, Mobile Buy SDK/docs/templates/html/index-template.html, Mobile Buy SDK/docs/templates/html/object-template.html
This reverts the documentation templates as we no longer need custom paths for hosted documentation. Links will now work correctly when the documentation is generated locally and used with apps such as Dash.
=> Fix paths so local documentation now links correctly

README.md
This fixes a small issue where links being relative means links on Cocoapods.org and Cocoadocs.org weren't working for Github: http://cocoadocs.org/docsets/Mobile-Buy-SDK/1.2.1/
=> Removed relative links for Github

Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m
Improves layout for the checkout footer by using the view controller's bottom layout guide.
@gabrieloc please review :eyes:
=> Use bottom layout margins instead of calculating offset using views

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.m, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayHelpers.m
Fix #68 
This fixes an issue where the `partialAddresses` flag was set to false, which would invalidate the already set (through a `updateCheckout:completion:` call) shippingRate on Shopify during a call to `completeCheckout:completion:`.
I have added more context to the usage of the `partialAddresses` property and we now override the setter to throw an `NSException` if this is ever set to `false`. This value should always ever be set to `true`.
I have removed the code that would have (and may have) set this property to `false` and added a test assertion that an exception is thrown if the value is set.
=> Fix shipping rate invalidation bug using Apple Pay in 1.2.2

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m, Mobile Buy SDK/Mobile Buy SDK/Utils/NSURLComponents+BUYAdditions.h, Mobile Buy SDK/Mobile Buy SDK/Utils/NSURLComponents+BUYAdditions.m
This PR primarily switches `/anywhere/checkouts` to the new `/api/checkouts` endpoint. However, I thought it was a good chance to switch over to using `NSURLComponents` to create all of the request URLs with, which consisted of some work to use the paths and query items that comes with it.
* `/anywhere/checkouts` -> `/api/checkouts`
* Use of `NSURLComponents` to create request URLs
* methods that take a url have been switched to `NSURL` for better consistency
* updated tests for collections with better assertions for the various components in a URL as well as query comparisons
@bgulanowski please review :eyes: and :tophat:
=> Updated API endpoints

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m, Mobile Buy SDK/Mobile Buy SDK/Utils/NSURLComponents+BUYAdditions.m
* Add additional HTTP method tests
* Improve method names for URL components generation
* Add constants for paths that are used more than once
* `NSDictionary` => `NSQueryItem`s category method can now accept empty strings and correct generate a parameter with a key only
* Using path `pathWithComponents:` and `stringByAppendingPathExtension:` on path creation
@bgulanowski Please review :eyes: and :tophat:
=> NSURLComponents improvements

Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.h, Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m, Mobile Buy SDK/Mobile Buy SDK/View Controllers/BUYViewController.h, Mobile Buy SDK/Mobile Buy SDK/View Controllers/BUYViewController.m
This moves and adds a few methods in `BUYViewController` from `BUYProductViewController` that handles the logic for whether to display the "Setup  Pay" button if Apple Pay is available on the shop and on the device, but not yet setup with a card.
This also fixes an issue where the "Setup  Pay" would display instead of "Buy with  Pay" in the `BUYProductViewController` due to using an incorrect getter method.
=> Fix Apple Pay "Setup" button logic

Mobile Buy SDK/Mobile Buy SDK/Models/BUYOrder.m
This removes an internal property that wasn't being used on the `BUYOrder`. It's always `nil` because it's not parsed or used anywhere.
This removes any confusion and makes it more obvious to use the `BUYObject.identifier`
=> Remove unused orderId property

Mobile Buy SDK/Mobile Buy SDK/Utils/BUYAddress+Additions.m
Fix #82 
This removed the requirement in Apple Pay for a province to exist on a shipping address. This solves the issue of merchants that ship worldwide and support Apple Pay.
=> Remove province requirement from client-side address validation

Mobile Buy SDK/Mobile Buy SDK Tests/BUYCheckoutTest.m, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.m
Fix #84 
`shipping_rate_id` is no longer required on Shopify. This is a `readonly` property, so there's no need to deprecate it. It can be removed without the need for any fallbacks.
=> Remove shippingRateId on BUYCheckout

Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/CheckoutViewController.m, Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/ProductListViewController.h, Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/ProductListViewController.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m, Mobile Buy SDK/Mobile Buy SDK/View Controllers/BUYViewController.m
Fix: #88 
- cleanup error handling for Apple Pay
- Use dispatch_groups to ensure the shop and checkout are completed before continuing with an Apple Pay checkout
- Use same merchant ID in both checkout flows in sample app
@runmad @cocoahero
=> Prevent race condition during Apple Pay Checkout

Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m
Fix: #94 
Uses the navigation bar from the navigation controller, which is accessible even when presented via a tabbar.
Please review: @gabrieloc
=> Fix crash when presenting product view controller from tabbar

Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout_Private.h
The `customerId` was being represented by an `NSString` when it is, in fact, returned from the API as an `NSNumber`.
Fixes #116 
=> Change customerID type from NSString to the correct type - NSNumber.

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
**What this does**
Adds new Debug and Release configurations for debugging Core Data, named `Debug-core-data` and `Release-core-data` respectively. These configurations define a macro named `CORE_DATA_PERSISTENCE`, which determine the inheritance of model classes.
Fixes #161 
@dbart01 @bgulanowski @davidmuzi
=> Core Data Configurations

Mobile Buy SDK/Mobile Buy SDK Tests/BUYPaymentProviderTests.m, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYApplePayPaymentProvider.m, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYPaymentProvider.h, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYWebCheckoutPaymentProvider.m, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYError+BUYAdditions.m
- Small change to method naming in `<BUYPaymentProviderDelegate>`
- Breaks up checkout error parsing into smaller methods
@bgulanowski @dbart01 @davidmuzi
=> Refactor payment provider

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
This is a simple project cleanup change.
There were two references to a header in both framework targets, and you don't want that. Probably caused by merge.
@dbart01 @gabrieloc
=> Remove duplicate references in target.

Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m
- adds a separate, private network queue for `NSURLSessionDataTask` requests
- minor refactoring and cleanup
Fixes #190 
=> Add separate network request queue to avoid deadlock. Minor refactor.

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest_Storefront.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
- adds missing API that allows fetching a product by its unique `handle`
- adds integration test for product handle API
Fixes #194 
Relies on #204
=> Add missing product handle API.

Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYOptionValue.m
This changes the test for equality in BUYOptionValue.
Without it, different values for the same option look equal, meaning some options will not show up with added to a set. A consequence was that in the Advanced Sample, all products show only one option.
Use the `value`, not the `optionId` (which is basically equivalent to using the `name`, since both refer to properties on the related `BUYOption`).
@dbart01 @davidmuzi @gabo
=> Fix equality test in BUYOptionValue

Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCart.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCart.m, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCollection.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCollection.m, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYOrder.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYOrder.m, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProduct.m, Mobile Buy SDK/Mobile Buy SDK/Models/Transient/BUYCheckout.h, Mobile Buy SDK/Mobile Buy SDK/Models/Transient/BUYCheckout.m, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYPaymentController.h, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYPaymentController.m
Using `CoreData` models required the use of `NSOrderedSet` for certain ordered collections. Since `NSOrderedSet` doesn't have a typed equivalent in Swift, none of the type information transfers over to Swift, making it very inconvenient to use those properties. Here, what we do is:
- add typed collections for `NSOrderedSet` properties
=> Add typed collection for Swift support.

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Mobile Buy SDK/Mobile Buy SDK/Buy.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Checkout.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Internal.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClientTypes.h, Mobile Buy SDK/Mobile Buy SDK/Operations/BUYCheckoutOperation.h, Mobile Buy SDK/Mobile Buy SDK/Operations/BUYCheckoutOperation.m, Mobile Buy SDK/Mobile Buy SDK/Operations/BUYStatusOperation.h, Mobile Buy SDK/Mobile Buy SDK/Operations/BUYStatusOperation.m, Mobile Buy SDK/Mobile Buy SDK/Static Framework/Buy.h
- adds status to `BUYStatusOperation` completion for internal use
- moves `BUYClient` types into separate header
@bgulanowski @gabrieloc
=> Improve support in private methods

Mobile Buy SDK/Mobile Buy SDK/Models/BUYModelManagerProtocol.h
Passing a nil predicate to the fetch request created in `-buy_purgeObjectsWithEntityName:` is legal.
@dbart01 @bgulanowski
=> Allow nil predicate in in Model Manager API

Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAdditions.h
The `buy_emailFromRecord:` method in BUYApplePayAdditions.h uses `ABRecordRef` which is deprecated by Apple as of iOS 9.0. Similar methods in the header are marked as deprecated but it looks like this one was missed. This PR just adds the proper deprecation markers so Xcode doesn't complain when using the framework on a iOS 9.0+ project.
Looking at what the method was doing, I don't believe a `buy_` replacement is necessary. Getting the email address from a `PKContact` is a single property access, as opposed to `ABRecordRef` which is lots of fun to get stuff out of.
Please review @bgulanowski
=> Mark buy_emailFromRecord as deprecated

Mobile Buy SDK/Mobile Buy SDK Tests/BUYCoreDataModelAdditionsTests.m, Mobile Buy SDK/Mobile Buy SDK Tests/TestModel.h, Mobile Buy SDK/Mobile Buy SDK/Additions/NSPropertyDescription+BUYAdditions.m
This enables support for assigning inverse relationship values for standard builds.
Fixes https://github.com/Shopify/mobile-buy-sdk-ios/issues/237
@davidmuzi
=> Assign inverse values for 1-to-1 and 1-to-N relationships

Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYWebCheckoutPaymentProvider.m
This allows checkout to continue if already started, if the checkout being passed in matches the one currently in progress.
This allows an app to continue an existing web checkout that the user interrupted. On iOS 8, when starting a checkout, we open Safari. If the user returns from Safari without finishing their checkout, perhaps to modify their cart, we should allow checkout to continue.
An alternative approach would be to put more onus on the app to make sure that the payment provider state is reset, but this is simple and should be safe.
@davidmuzi @gabrieloc
=> Improve consistency check when starting checkout

Mobile Buy SDK/Mobile Buy SDK/Operations/BUYRequestOperation.m
For group operations, we need to be able to cancel dependent operations if an operation fails. This will only work if the failed operation has not been declared finished. Determination of success or failure happens in the completion block attached to the operation. So we must execute that completion block to evaluate success before we mark finished. Otherwise, the successive, dependent operations will get executed concurrently with evaluating success/failure, and cause bad things to happen.
This particularly affected the checkout status check. When we get a 424 response for a checkout that was not completed, we don't want to get the checkout, since nothing has changed. Getting the checkout is treated as proof that the previous operation (get status) succeeded, and we always return assume …
=> Execute completion blocks before marking as finished

Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYProduct.m
This removes the public URL from the product entity, as it is not sent by Shopify
@bgulanowski
=> Remove public product url

Mobile Buy SDK Sample Apps/Sample App Customers/Sample App Customers/OrdersViewController.swift
The customer sample app is written in Swift, and has an extension on BUYOrder to type the array of line items (which is exposed as an NSOrderedSet in the SDK.  To avoid a naming conflict, this change modifies the method name in the sample app.
@bgulanowski
=> Fix customer app

Mobile Buy SDK Sample Apps/Sample App Swift/Mobile Buy SDK Swift Sample/Config.swift, Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+StorefrontTests.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
The type for ID in the product model is NSNumber.  We should use the same type in the APIs.
@bgulanowski
=> Use NSNumber for product id in Client APIs

Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/LoginViewController.swift, Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/OrdersViewController.swift, Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/SignupViewController.swift, Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m, Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+RoutingTests.m, Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Mobile Buy SDK/Mobile Buy SDK/Buy.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Address.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Address.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Customers.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Customers.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Routing.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Routing.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m, Mobile Buy SDK/Mobile Buy SDK/Models/BUYAccountCredentials.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYAccountCredentials.m, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCustomerToken.h, Mobile Buy SDK/Mobile Buy SDK/Models/BUYCustomerToken.m, Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYWebCheckoutPaymentProvider.m
The customer authentication (token creation) endpoint provided by Shopify returns an access token (`customer_access_token`) object. This includes three attributes: `customer_id`, `expires_at` and `access_token`. Up until now, the buy client has been keeping a reference to the token string, using the customer ID to fetch the customer, and throwing away the expiry date.
On Android, in contrast, we keep a reference to the entire access token.
As a consequence, APIs that require a customer to be authenticated can use the `customerID` from the access token, instead of a needing a parameter.
This PR updates the behaviour to match Android, keeping a reference to the entire access token.
We have renamed a private class to `BUYCustomerToken` and made it public. Callbacks now return this object, …
=> Introduce BUYCustomerToken and update APIs

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Customers.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Customers.m
Fix: #272 
Adds support for the update customer endpoint.  Removes pointless customer update unit test.
@bgulanowski
=> Add customer update endpoint

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+StorefrontTests.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
To support shared links from the web for collections, we must be able to fetch a collection by the handle used in the link. Parity with Android.
New storefront API method that accepts a handle as a string, returns a collection.
@gabrieloc @krisorr
=> Add support to get collection with handle

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m, Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYAddress.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYAddress.m
Add `isDefault` attribute to `Address` entity.
We will add additional conveniences for making sure that setting the default address on a customer behaves nicely. For now, change the value directly on the correct address, and ensure any other addresses are no longer marked as default.
Fixes #277 
@gabrieloc @krisorr
=> Add "Address.isDefault" boolean <-> "default"

README.md
Removed Swift sample app link in README, and replaced broken links.
The new sample app links to their respective folders instead of README.md which the old links linked too, since their respective folders display the README.md anyways
@bgulanowski @gabrieloc
=> Removed Swift sample app link in README, and replaced broken links

Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
This puts arguments in the correct order when invoking the completion block.
This causes a compiler error when built for device:
```
mobile-buy-sdk-ios/Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m:140:48: error: implicit conversion loses integer precision: 'const NSUInteger' (aka 'const unsigned int') to 'BOOL' (aka 'signed char') [-Werror,-Wconversion]
block(tags, [self hasReachedEndOfPage:tags], page, error);
~~~~~                                        ^~~~
```
But this issue is not caught when building for simulator.
@gabrieloc @davidmuzi
=> Args are in wrong order.

Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Checkout.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Checkout.m
completeCheckout: was returning a private class BUYOperation.  When using the Buy framework in Swift the completeCheckout: method was not available because of the private class return type.  I changed the return value for the method to NSOperation which lets the method be available.  Alternatively you could make BUYOperation public.
=> change completeCheckout: return value from BUYOperation to NSOperation

Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/ProductView.h, Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/ProductView.m, Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/ProductViewController.m, Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/View Controllers/PaymentViewController.m
Fix: #304 
This fixes a bug in the sample app that prevents the Apple Pay button from appearing
Removes a duplicate call to setup the button, which was using the wrong boolean value.
@bgulanowski
=> Fix Apple Pay button logic in PaymentViewController

Mobile Buy SDK/Mobile Buy SDK Tests/BUYRequestOperationTests.m
The test to cancel an operation after it has already started (and before it completes) has been crashing sporadically with a memory access exception. Cause not really known.
This simplifies the test somewhat to create and fulfill an expectation the more common way. Very much a shot in the dark.
Also add some more assertions.
@gabrieloc @dbart01
=> Update test to remove delay and add explicit expectation

Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents, Mobile Buy SDK/Mobile Buy SDK/Models/Transient/_BUYShippingRate.h, Mobile Buy SDK/Mobile Buy SDK/Models/Transient/_BUYShippingRate.m
`ShippingRate` was incorrectly given an `identifier` property when the model was converted for SDK version 2. `identifier` may have been intended to replace `shippingRateIdentifier`, but that would have been inappropriate in any case, as the `shippingRateIdentifier` is a string, not a number.
Fixes https://github.com/Shopify/mobile-buy-sdk-ios/issues/313
cd @davidmuzi @gabrieloc for review
=> Remove `identifier` property from `ShippingRate` entity.

Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/ProductListViewController.m
The method signature for fetching products has changed in 2.0, this PR updates the call in the Advanced Sample App
@bgulanowski
=> fix product fetch signature in sample app

.gitignore, Mobile-Buy-SDK.podspec
* Add weak qualifier to `PassKit` framework dependency in podspec.
* Resolves [#297](https://github.com/Shopify/mobile-buy-sdk-ios/issues/297)
* Additionally added `.DS_Store` to .gitignore.
=> Fix 'Symbol not found' issue with iOS 9 and Cocoapods.

Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYWebCheckoutPaymentProvider.m
Fix: #355
- Clears out the checkout object after the delegate is called
@bgulanowski
=> Move nilling out of checkout to after notification is sent

Mobile Buy SDK/Mobile Buy SDK Tests/BUYProductTests.m, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProduct.m, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYProduct.h, Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYProduct.m
This adds a new local-only property to BUYProduct. This enables easier sorting of products in collections. This improves parity with the Android SDK, which already has this property.
It might seem more natural to perform this change in the `-setVariants:` method. However, when Core Data support is enabled, `-setVariants:` is not called when updating from JSON. In any case, we don't support modifying relationships of storefront objects. This objects are read-only.
*\* Discussion **
Strictly, `-setVariants:` is not called from `-setValuesForKeysWithDictionary:`, even though it builds on `-setValue:forKey:`, which should call the custom setter. It doesn't. It is probably because the getter is not implemented, therefor KVC is not complete for that property.
In any case overriding relationship …
=> Add minimumPrice property to BUYProduct (take 2)

Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYApplePayPaymentProvider.m
Check integer value instead of NSNumber pointer when assigning required fields
Resolves #397 
=> [#397] Fix ternary operator assignment for Apple Pay Shipping Address Required Fields 

Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Base.lproj/Main.storyboard
Make product image views square with a content mode of aspect fill so that product images look good in all orientations and dimensions.
Resolves #448 
=> [#448] Make product image view square and aspect fit

Mobile Buy SDK/Mobile Buy SDK Tests/BUYPaymentProviderTests.m, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYApplePayPaymentProvider.m, Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYPaymentProvider.h, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAuthorizationDelegate.h, Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAuthorizationDelegate.m
Adopt `PKPaymentAuthorizationControllerDelegate` for Apple Pay specific classes and use system version checking to use `PKPaymentAuthorizationController` instead of `PKPaymentAuthorizationViewController`.
This will allow us to use the current Apple Pay classes for watchOS.
Resolves #245 
=> [#245] Support PKPaymentAuthorizationController for iOS 10.0+

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Scripts/run_tests.sh
Don't pull the shell from $SHELL because $SHELL could be anything, but
what is really desired is a POSIX-compliant shell (ie. /bin/sh)
=> Fix the build for non-POSIX compliant shells (ie. fish)

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Buy.xcscheme, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Mobile Buy SDK Tests.xcscheme, Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Static Universal Framework.xcscheme
Xcode 8.2 came out a while ago. Xcode randomly decided to change the version marker in these files. If we don't commit them, it will just keep making this changes.
=> Xcode version noise

Buy/GraphClient.swift
Remove nullability for `URLSession`. We always have one, there's no point having it declared `Optional`. Taking advantage of non-nil `URLSession`, we can also return non-nil `URLSessionDataTask`s.
=> Graph client

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/AppDelegate.swift, Sample Apps/Storefront/Storefront/Assets.xcassets/AppIcon.appiconset/Contents.json, Sample Apps/Storefront/Storefront/Base.lproj/LaunchScreen.storyboard, Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard, Sample Apps/Storefront/Storefront/CollectionsController.swift, Sample Apps/Storefront/Storefront/Info.plist
Creates a blank sample application that will showcase the usage of the SDK. The plan is to have this app show off the following:
- hybrid collection view
- products grid
- product details
- cart / checkout
- Apple Pay integration
There isn't much to review here as it's mostly a standard Xcode template for a single-view app. The only extra things done here is removal of annoying comment templates and addition of license headers.
Fixes #512
=> Create blank sample application called Storefront.

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard, Sample Apps/Storefront/Storefront/CollectionCell.swift, Sample Apps/Storefront/Storefront/CollectionCell.xib, Sample Apps/Storefront/Storefront/CollectionViewModel.swift, Sample Apps/Storefront/Storefront/CollectionsViewController.swift, Sample Apps/Storefront/Storefront/Fragment+Collection.swift, Sample Apps/Storefront/Storefront/Fragment+CollectionQuery.swift, Sample Apps/Storefront/Storefront/Fragment+ImageConnectionQuery.swift, Sample Apps/Storefront/Storefront/Fragment+Product.swift, Sample Apps/Storefront/Storefront/Fragment+ProductConnectionQuery.swift, Sample Apps/Storefront/Storefront/Fragment+Shop.swift, Sample Apps/Storefront/Storefront/NSObject+Name.swift, Sample Apps/Storefront/Storefront/ProductCell.swift, Sample Apps/Storefront/Storefront/ProductCell.xib, Sample Apps/Storefront/Storefront/ProductViewModel.swift, Sample Apps/Storefront/Storefront/StorefrontCollectionView.swift, Sample Apps/Storefront/Storefront/StorefrontTableView.swift, Sample Apps/Storefront/Storefront/UIImageView+Remote.swift, Sample Apps/Storefront/Storefront/ViewModel.swift, Sample Apps/Storefront/Storefront/ViewModelConfigurable.swift, Sample Apps/Storefront/Storefront/ViewModeling.swift
__NOTE:__ Don't get overwhelmed by the line change count. Nearly 500 lines are header comments. There's also a bunch of storyboard / nib files that you're better off looking at in Xcode.
Adds a hybrid collection view to display collections (vertically) and products (horizontally). 
Here, we also set the groundwork for `ViewModel` support with the 3 primary classes:
- `ViewModel.swift` - view models will implement this protocol
- `ViewModeling.swift` - objects that can be represented by a view model will implement this protocol
- `ViewModelConfigurable.swift`- objects that can be configured using a view model will implement this protocol
To alleviate the pain of digging through connections & edges and to simplify query building, extensions on `Storefront` objects were introduced that …
=> Collections hybrid view

Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
Object identifiers are numbers, not strings.
As a consequence, we need to support a `nil` value for collection ID when fetching product tags.
=> Fix argument types in client API

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard, Sample Apps/Storefront/Storefront/CollectionCell.xib, Sample Apps/Storefront/Storefront/CollectionViewModel.swift, Sample Apps/Storefront/Storefront/CollectionsViewController.swift, Sample Apps/Storefront/Storefront/GraphClient+Shared.swift, Sample Apps/Storefront/Storefront/ProductViewModel.swift, Sample Apps/Storefront/Storefront/ProductsViewController.swift, Sample Apps/Storefront/Storefront/Storyboard+ViewController.swift
Adds a products grid using a `UICollectionView`. Also makes some minor adjustment to the `ViewModel` family of protocols to store the original model inside the view model. Doing so, allows us to pass around view models in the UI layer but still have access to underlying properties (namely GraphQL ID) for queries and mutations.
=> Add product collection view.

Buy/Generated/Storefront/Domain.swift, Buy/Generated/Storefront/Image.swift, Buy/Generated/Storefront/Order.swift, Buy/Generated/Storefront/ShopPolicy.swift, Scripts/update_schema
Adds a custom `URL` scalar and serializer / deserializer as part of the schema generation script. Doing so allows us to use the native `URL` type in Swift foundation instead of a `String` representing the URL.
Most of the changes are auto-generated. The only manual additions are to `update_schema`.
cc: @sav007 Not sure if this is possible / applicable to Android.
=> Custom URL scalar

Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
This fixes two bugs at once.
First, we were indexing into an array that could be empty, leading to a crash.
Second, we don't want to create a collection model if we didn't receive one.
I don't consider this an error, but clients will have to support a `nil` result.
=> Do not create a collection model without JSON content

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/ImageViewController.swift
Adds a custom `ImageViewController` subclass to abstract the display of pageable product images. The controller takes a collection of `ImageItem`s that can either represent an image URL or bitmap. This `ImageViewController` uses a `UICollectionView` with a custom cell to represent the images on screen. It also provides automatic `UIPageControl` configuration to help the user identify the image index they're looking at.
=> Image collection

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard, Sample Apps/Storefront/Storefront/CollectionViewModel.swift, Sample Apps/Storefront/Storefront/GraphQuery.swift, Sample Apps/Storefront/Storefront/HTMLParser.swift, Sample Apps/Storefront/Storefront/ProductDetailsCell.swift, Sample Apps/Storefront/Storefront/ProductDetailsCell.xib, Sample Apps/Storefront/Storefront/ProductDetailsViewController.swift, Sample Apps/Storefront/Storefront/ProductHeaderCell.swift, Sample Apps/Storefront/Storefront/ProductHeaderCell.xib, Sample Apps/Storefront/Storefront/ProductViewModel.swift
Implements the rest of product details. Since product descriptions are provide in HTML, we needed to implement an HTML -> `NSAttributedString` converter. This class is called `HTMLParser`. It handles the styling and conversion of HTML into a useable attributed string that we display using a simple `UILabel`. Font names and sizes are injected into the HTML string using `<style></style>` tags as this is the only way to apply formatting to the provided HTML.
The product details are displayed using two types of cells:
- `ProductHeaderCell`
- `ProductDetailsCell`
=> Product information and HTML parsing.

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/CartController.swift, Sample Apps/Storefront/Storefront/CartItem.swift, Sample Apps/Storefront/Storefront/CartItemViewModel.swift, Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/GraphQL+Serializable.swift, Sample Apps/Storefront/Storefront/Serializable.swift, Sample Apps/Storefront/Storefront/ViewModel.swift
- adds Serializable protocol that all GraphQL entities automatically conform to by extending AbstractResponse
- conforms `CartItem` to Serializable
- enables `CartController` to flush cart items to disk on a background thread whenever there’s changes
- enables `CartController` to read from cached cart on disk during initialization
=> Add support for persisting CartItem(s) to disk.

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/ProductDetailsCell.swift, Sample Apps/Storefront/Storefront/String+HTML.swift
Get rid of the poorly-named `HTMLParser` class and moves the functionality to a `String` extension.
=> HTML to attributed string

Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj, Mobile Buy SDK/Mobile Buy SDK/Buy.h, Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Internal.h
This exposes the internal API of the BUYClient to allow subclasses to hook into some behaviours.
=> Support subclassing of BUYClient

Mobile Buy SDK/Mobile Buy SDK/Utils/BUYError+BUYAdditions.m
Improves validation message for invalid variant_id.
Resolves https://github.com/Shopify/instant-app/issues/133
In case when checkout refresh contains variant_id of the object that is not present in the channel, validation message (obtained through `-[BUYError quantityRemainingMessage]`) is ambiguous in the sense that it assumes there was issue with remaining quantity, but actual error message contains `invalid` code and no options that is assumed to be present.
Proposed change is to detect that case and show more meaningful error message for that context.
In order to test this scenario one need to reference variant_id that is not present in the channel. I was testing on Instant-app generated for puravida shop. I altered code making checkout refresh call to following
```
- (NSOperation …
```
=> Improve checkout validation message

Buy.xcodeproj/project.pbxproj, Pay/Info.plist, Pay/PassKit+Extensions.swift, Pay/Pay.h, Pay/PayAddress.swift, Pay/PayCheckout.swift, Pay/PayController.swift, Pay/PayCurrency.swift, Pay/PayLineItem.swift, Pay/PayShippingRate.swift, PayTests/Info.plist, PayTests/PayTests.swift, Sample Apps/Storefront/Storefront/CartController.swift
**TLDR;** 👀  needed. If you're gonna review any PR from the SDK, this is the one to review. Also, please ignore the ludicrous `1080 additions`, a lot of is the project file and file header comments. This PR should be very reviewable.
The purpose of `PayController` and this abstraction is to provide the easiest solution for developers to integrate with  Pay. The intention is to limit *all* possible  Pay implementation to a reasonably-flexible, `PayCheckout` focused solution that doesn't require people to read the documentation for an hour to figure out how to use it. If you feel confused looking at this API, this is a red flag.
Adds a target and framework called `Pay` that encapsulates everything developers will need to support Apple Pay. It is a separate target to maintain separation …
=> Apple Pay integration

Buy.xcodeproj/project.pbxproj, Pay/PayAddress.swift, Pay/PayAuthorization.swift, Pay/PayCheckout.swift, Pay/PaySession.swift, Pay/PayShippingRate.swift
Renames `PayController` to `PaySession` and encapsulates a payment authorization in `PayAuthorization` to provide all necessary info to complete a checkout after successful  Pay invocation.
**NOTE: Disregarding failing tests, requires Xcode 8.3.***
=> Pay session

Pay/PayAuthorization.swift, Pay/PaySession.swift, PayTests/PayAuthorizationTests.swift, PayTests/PaySessionTests.swift
Fix how `PKPayment` token is handled before passing it off to a `completeCheckout` query. It needed to be a simple string instead of a hex string representing the data.
=> Authorization token

Pay/PayCheckout.swift, PayTests/Models.swift, PayTests/PayCheckoutTests.swift
The checkout ID was mistakenly removed because it was thought to be unused. In fact, it's used for updating and completing checkout. So it's back.
=> Checkout ID

.buildkite/pipeline.yml, Scripts/run_tests.sh, Scripts/test_buy, Scripts/test_pay
Previously, the SDK build process involved a single script that would "run tests". The path to this script along with any required environment variables were hard-coded in Buildkite admin making it very difficult (impossible) to have custom build environments on different branches.
Also, in SDK 3.0 we have two independent targets that needs testing. With a single script, we can't parallelize the builds.
Migrate to using a `pipeline.yml` file that would setup the build pipeline dynamically. Doing so, allows us to setup steps and environment as needed on any specific branch, as well as, run multiple target's tests in parallel.
Adding the `pipeline.yml` required an addition hard-coded step in Buildkite to ensure backwards compatibility with the previous method. It would upload the pipeline …
=> Buildkite pipeline

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/AddressViewModel+PayAddress.swift, Sample Apps/Storefront/Storefront/AddressViewModel.swift, Sample Apps/Storefront/Storefront/CartController.swift, Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/CheckoutViewModel+PayCheckout.swift, Sample Apps/Storefront/Storefront/CheckoutViewModel.swift, Sample Apps/Storefront/Storefront/Client.swift, Sample Apps/Storefront/Storefront/ClientQuery.swift, Sample Apps/Storefront/Storefront/CollectionsViewController.swift, Sample Apps/Storefront/Storefront/CreditCardViewModel.swift, Sample Apps/Storefront/Storefront/Fragment+CheckoutQuery.swift, Sample Apps/Storefront/Storefront/LineItemViewModel.swift, Sample Apps/Storefront/Storefront/PaymentViewModel.swift, Sample Apps/Storefront/Storefront/ProductsViewController.swift, Sample Apps/Storefront/Storefront/ShippingRateViewModel+PayShippingRate.swift, Sample Apps/Storefront/Storefront/ShippingRateViewModel.swift
Adds  Pay checkout to the sample app using `PaySession`.
The majority of this PR contains no behaviour. For the most part it's mapping between models and view models and introducing more models. What does have some reviewable behaviour is the `CartViewController` that is actually responsible for  Pay checkout.
NOTE: `Client.swift` was renamed from `Graph.swift` but for some reason it shows up as an addition.
=>  Pay Checkout

Buy/Graph.Client.swift, BuyTests/Graph.ClientTests.swift
Adds a default client-wide `CachePolicy` that will be extended to each `query` operation if no cache policy is provided. Add tests for this behaviour.
=> Client cache policy

Sample Apps/Storefront/Storefront/CollectionsViewController.swift
The index being passed to products view controller was a row index instead of a section index.
=> Fix collection index

.travis.yml, Scripts/test_buy, Scripts/test_pay
Fixes issues with TravisCI not recognizing `xcpretty` and using incorrect simulator versions. Using  `OS=latest` we can ensure that builds don't brake with a new release of iOS / Xcode / Simulators.
=> Update CI configuration.

Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/ProductDetailsViewController.swift
Building and running with Xcode 9 revealed some issues surrounding how `UITableView` configures self-sizing cells. Explicit assignments of `UITableViewAutomaticDimension` for `rowHeight` fix the layout issues encountered when building with the new iOS 11 SDK.
=> UITableView estimated height

Buy.xcodeproj/project.pbxproj, Buy.xcodeproj/xcshareddata/xcschemes/Buy.xcscheme, Buy.xcodeproj/xcshareddata/xcschemes/BuyTests.xcscheme, Buy.xcodeproj/xcshareddata/xcschemes/Crypto.xcscheme, Buy.xcodeproj/xcshareddata/xcschemes/CryptoTests.xcscheme, Buy.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
Update Xcode project code signing to have no team by default. Also updates the deployment targets for build products as follows:
- `Buy.framework` ~> iOS 8.0 and up
- `Pay.framework` ~> iOS 10.0 and up
- `Crypto.framework` ~> iOS 9.0 and up
Fixes #636
=> Xcode configuration

Buy/Generated/Storefront/Customer.swift, Buy/Generated/Storefront/CustomerCreateInput.swift, Buy/Generated/Storefront/CustomerUpdateInput.swift, Buy/Generated/Storefront/MailingAddress.swift, Buy/Generated/Storefront/Order.swift, Buy/Generated/Storefront/OrderSortKeys.swift, Buy/Generated/Storefront/ProductVariant.swift, Buy/Generated/Storefront/Shop.swift
Runs the automated update routine and introduces the following changes to the generated schema:
- reduce supported query parameters for `Customer.orders`
- add `phone` parameter to `CustomerCreateInput`
- add `phone` parameter to `CustomerUpdateInput`
- add `formattedArea` to `MailingAddress`
- reduce sort keys exposed for customer orders
- add `availableForSale` instead of `available` in `ProductVariant`
- add ability to fetch a collection or product by handle
Will need similar on Android: @sav007
=> Schema update

Buy/Card/Card.CreditCard.swift, BuyTests/Card/Card.CreditCardTests.swift
Fixes the payload sent to card server for obtaining a `vaultID` used for credit card checkout. 
Fixes #673
=> Fix Card.CreditCard payload.

README.md
Updates README to fix incorrect reference to `cardUrl`.
Fixes #680
=> Update README to fix incorrect reference to `cardUrl`

Mobile Buy SDK/Mobile Buy SDK/Additions/NSDateFormatter+BUYAdditions.m
Fixes date initialization fail for case when user locale is in UTC-0 and time format is set as non 24-hour.
Date formatter locale is set to "us_GB" instead of currentLocale if 12-hour time format is set in user settings.
Fixes #665
=> Fix date initialization for 12hour time format in UTC-0 region.

Pay/PayAddress.swift, Pay/PaySession.swift, PayTests/Mocks/MockSessionDelegate.swift, PayTests/PaySessionTests.swift, Sample Apps/Storefront/Storefront/CartViewController.swift
Adds a new delegate callback for `PaySession` that notifies delegates about shipping address updates. Since billing address isn't available until the end of the Apple Pay flow, we have to require the shipping address even for checkouts that don't require shipping so that we can ask Shopify for relevant tax information to update the subtotal. If we don't do so, the end-user would be authorizing the payment for a subtotal that doesn't include taxes and the amount mismatch would cause the transaction to fail.
Also, allows `PayAddress` to handle a `nil` postal address coming from `PKContact`.
Fixes #696
=> Improved support for checkouts that don't ship

Buy.xcodeproj/project.pbxproj, Pay/PassKit+PayCardBrand.swift, Pay/PayCardBrand.swift, Pay/PaySession.swift, PayTests/PayCardBrandTests.swift
Currently, `PaySession` hardcodes supported card types for Apple Pay payment requests. Not all stores will support all card types. This allows `PaySession` to be configured with supported card types for the payment request.
=> Card brands

Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/Client.swift, Sample Apps/Storefront/Storefront/ClientQuery.swift
Updates the sample app to fix an issue where the checkout wasn't being updated with the full shipping address before being completed. 
PassKit only provides a partial address sufficient enough to request shipping rates and update the checkout with the preferred shipping method. The complete address containing the name and the first address line isn't provided until the payment is authorized. As a result, we have to update the shipping address twice.
Fixes #705
=> Update shipping address before checkout

Pay/PayAddress.swift, Pay/PaySession.swift, PayTests/PayAddressTests.swift, README.md, Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/AddressViewModel+PayAddress.swift, Sample Apps/Storefront/Storefront/AddressViewModel.swift, Sample Apps/Storefront/Storefront/ClientQuery.swift, Sample Apps/Storefront/Storefront/Fragment+CheckoutQuery.swift
In Canada and United Kingdom, PassKit vends only partial postal codes. Shopify isn't able to yield shipping rates for partial codes in these countries and so we must pad them on the client. This is done **only** for Canada and United Kingdom. Partial zip codes for United States and other countries are left untouched.
=> Support for partial postal codes.

Buy.xcodeproj/project.pbxproj, Buy.xcodeproj/xcshareddata/xcschemes/Buy watchOS.xcscheme
Since WatchKit runs on a different architecture, it requires a dedicated watchOS framework. This adds a `Buy watchOS` target.
Fixes #738
=> Buy watchOS target

Buy/Client/Graph.Cache.swift
Assigns a framework version to the cache directory. Doing so pins each set of cached queries to the framework version, effectively eliminating any cached data from leaking across releases.
Fixes #719
=> Invalidate cache across version bumps.

Buy.xcodeproj/project.pbxproj, Buy.xcodeproj/xcshareddata/xcschemes/Buy tvOS.xcscheme, Scripts/test_buy_tv, Scripts/test_buy_watch, circle.yml
- adds target for `tvOS`
- adds build scripts to CI for verifying that the `watchOS` and `tvOS` targets build correctly
Fixes #748
=> Target for tvOS

Buy/Generated/Storefront/CheckoutAttributesUpdateInput.swift, Buy/Generated/Storefront/CheckoutCreateInput.swift, Buy/Generated/Storefront/CheckoutLineItemInput.swift, Buy/Generated/Storefront/CheckoutLineItemUpdateInput.swift, Buy/Generated/Storefront/CreditCardPaymentInput.swift, Buy/Generated/Storefront/CurrencyCode.swift, Buy/Generated/Storefront/CustomerCreateInput.swift, Buy/Generated/Storefront/CustomerUpdateInput.swift, Buy/Generated/Storefront/MailingAddressInput.swift, Buy/Generated/Storefront/TokenizedPaymentInput.swift
Fixes an issues where deprecated input object initializers were assigning `.orNull` values instead of `.orUndefined` values.
=> Undefined values

Pay/PayCheckout.swift, Pay/PaySession.swift, PayTests/Models/Models.swift, PayTests/PayCheckoutTests.swift, PayTests/PaySessionTests.swift, Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/Client.swift, Sample Apps/Storefront/Storefront/ClientQuery.swift
Updates `PaySession` to require a `shopName` for creating Apple Pay payment sessions. A shop name is required to accurately reflect the entity to which the payment is being made by the customer.
Updates tests and sample app.
Fixes #781
=> Require shopName for PaySession

Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/CheckoutViewModel+PayCheckout.swift
Fixes an issue in the sample that cause the Apple Pay dialog to accumulate incorrect values during checkout.
Fixes #861
=> Fix incorrect subtotal in Apple Pay dialog.

Buy/Client/Graph.Task.swift, BuyTests/Client/Graph.TaskTests.swift
Remove the overhead of creating a task in the `isCancelled == true` state. Previously, we would create a task and only check if it's `.suspended` to determine whether to `resume()` it or not. Now, we check the cancelled flag before doing any of the above.
Adds test to verify behaviour.
=> Ignore retries for cancelled tasks, no completion.

README.md
This PR updates the README to include info on the mandatory shipping address and line that must be added to a checkout if a line item requires shipping.
Fixes https://github.com/Shopify/shopify/issues/160953
=> Update README with shipping requirements on checkout

Sample Apps/Storefront/Storefront/Client.swift
Avoid the cache when fetching shipping rates.
=> Avoid the cache when fetching shipping rates.

Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj, Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard, Sample Apps/Storefront/Storefront/CartViewController.swift, Sample Apps/Storefront/Storefront/Client.swift, Sample Apps/Storefront/Storefront/ClientQuery.swift, Sample Apps/Storefront/Storefront/WebViewController.swift
Adds support for associating a currently logged-in user with a checkout. Using a `WKWebView` is necessary since a custom header is required to transfer authentication state to web checkout.
=> Associate logged-in use with web checkout.

Buy/Utilities/Global.swift
Updates to how we determine and send the SDK version in request headers. This a more reliable alternative to `CFBundleVersionKey`. CocoaPods doesn't respect that value and uses `1` instead. Migrating to "short version" string instead fixies the problem.
=> Use short bundle version, it’s more reliable.

Buy/Generated/Storefront/CheckoutAttributesUpdatePayload.swift, Buy/Generated/Storefront/CheckoutCompleteWithCreditCardPayload.swift, Buy/Generated/Storefront/CheckoutCompleteWithTokenizedPaymentPayload.swift, Buy/Generated/Storefront/CheckoutCompleteWithTokenizedPaymentV2Payload.swift, Buy/Generated/Storefront/CheckoutCustomerDisassociatePayload.swift, Buy/Generated/Storefront/CheckoutDiscountCodeApplyPayload.swift, Buy/Generated/Storefront/CheckoutEmailUpdatePayload.swift, Buy/Generated/Storefront/CheckoutErrorCode.swift, Buy/Generated/Storefront/CheckoutGiftCardApplyPayload.swift, Buy/Generated/Storefront/CheckoutGiftCardRemovePayload.swift, Buy/Generated/Storefront/CheckoutGiftCardRemoveV2Payload.swift, Buy/Generated/Storefront/CheckoutGiftCardsAppendPayload.swift, Buy/Generated/Storefront/CheckoutLineItemsAddPayload.swift, Buy/Generated/Storefront/CheckoutLineItemsRemovePayload.swift, Buy/Generated/Storefront/CheckoutLineItemsUpdatePayload.swift, Buy/Generated/Storefront/CheckoutShippingAddressUpdatePayload.swift, Buy/Generated/Storefront/CheckoutShippingAddressUpdateV2Payload.swift, Buy/Generated/Storefront/CheckoutShippingLineUpdatePayload.swift, Buy/Generated/Storefront/DigitalWallet.swift, Buy/Generated/Storefront/Image.swift, Buy/Generated/Storefront/QueryRoot.swift, Buy/Generated/Storefront/Shop.swift
- Adds `checkoutUserErrors` to several checkout-mutating fields
- Adds support to query for products by `availableForSale` status
=> Update schema (auto-generated).

Buy.xcodeproj/project.pbxproj
This changes TARGETED_DEVICE_FAMILY for Buy tvOS to 3, and TARGETED_DEVICE_FAMILY for Buy watchOS to 4.  
**Fixes:**
This fixes Carthage build failures for Buy tvOS and Buy watchOS.  The issue has not been previously logged.
=> Sets TARGETED_DEVICE_FAMILY for Buy tvOS and Buy watchOS to correct values.

Buy/Generated/Storefront/AppliedGiftCard.swift, Buy/Generated/Storefront/Checkout.swift, Buy/Generated/Storefront/CheckoutCreateInput.swift, Buy/Generated/Storefront/CurrencyCode.swift, Buy/Generated/Storefront/PaymentSettings.swift, Buy/Generated/Storefront/PricingValue.swift, Buy/Generated/Storefront/ProductVariant.swift, Buy/Generated/Storefront/ScriptDiscountApplication.swift, Buy/Generated/Storefront/ShippingRate.swift, README.md
PR to bump schema. Schema changes include:
**Multi Currency**
- Add `enabledPresentmentCurrencies` to payment settings.
- Add `amountUsedV2`, `balanceV2`, `paymentDueV2`, `subtotalPriceV2`, `totalPriceV2`, `totalTaxV2`.
- Deprecate  `amountUsed`, `balance`, `paymentDue`,  `subtotalPrice`, `totalPrice`, `totalTax`.
**Support**
- Add currency support for Panamian Balboa.
- Add `title` to script discount application query.
- Add `lineItemsSubtotalPrice` as a field returned on checkout.
=> Bump schema.

README.md
Fix queries sample code in README that didn't seem to compile in my test app (to learn the Buy SDK), using Xcode 10.2 and Swift 5.0.
Compilation error message I had:
"Contextual type for closure argument list expects 1 argument, which cannot be implicitly ignored"
Note: This is new pull request in the correct "develop" branch. I had previously made a pull request in "master" (https://github.com/Shopify/mobile-buy-sdk-ios/pull/982).
<# Describe your changes #>
Added a missing "$0" to a call to "Storefront.buildQuery" in the Queries sections of the README tutorial.
Fixes <# issue number #>
=> Fix queries sample code in README

README.md
Adds a link to the help center iOS buy SDK documentation to the readme's **Help** section.
https://github.com/Shopify/help/issues/7359
=> Add help center link

README.md
We forked this repo to make some changes to the internal/private declarations for Apple Pay and ran into issues installing as it pertained to the associated submodule connected to this repo. Clearing this up for future developers who may fork this.
Example: `pod 'Mobile-Buy-SDK', git: 'git@github.com:company-name/mobile-buy-sdk-ios.git', branch: 'your-branch', submodules: true`
=> Update readme to include submodules: true in Podfile

Buy.xcodeproj/project.pbxproj, Buy/Client/Graph.Client.swift, Buy/Utilities/Locale+Language.swift, BuyTests/Utitlies/Locale+LanguageTests.swift
Separates extension on `Locale` into a separate file, adds tests and support for `scriptCode` in multi-component language codes. See tests for details.
=> Locale tests

Buy/Client/Graph.Client.swift, README.md
Update sdk readme on how to get translated data for their dynamic content. See corresponding [release notes](https://shopify.dev/concepts/about-apis/versioning/release-notes/2020-01) on _Retrieving translated content with storefront API_ 
CC: @Shopify/api-documentation @Shopify/documentation
=> Update readme to catch locale usage

.github/workflows/test_pod_version.yml
The current git command only works sometimes, as evidenced by it's last run. Using git diff is more stable for what we want here.
=> Update test_pod_version with more stable diff

.github/workflows/deploy.yml
Deploy failed with `error: use of undeclared type 'GraphQL'` which I'm guessing is because it didn't grab the sub-modules on checkout.
See failed run here: https://github.com/Shopify/mobile-buy-sdk-ios/runs/574263599
=> Get git submodule before deploy

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
set-env was deprecated at the end of last year
Removes set-env. Looking at the script, I'm not sure this was actually doing anything.
=> Update actions to use GITHUB_ENV file instead of set-env

README.md
The README.md did not include information about polling for checkout readiness.
As checkouts may have asynchronous operations that can take time to finish polling for checkout readiness is required to ensure fields such as duties and taxes are populated.
The corresponding PR to update the sample project: https://github.com/Shopify/mobile-buy-sdk-ios-sample/pull/8
=> Update documentation with info about Checkout.ready polling
