- Mobile Buy SDK/Mobile Buy SDK/Models/BUYOrder.h
- Mobile-Buy-SDK.podspec
> Point podspec to public repo

- README.md
This resolves the Cocoapods badge, it's case-sensitive.
@davidmuzi Please review :eyes:
> Capital letters for Cocoapods badge

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Sample App Web/Mobile Buy SDK Web Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
> Remove team IDs

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Models/BUYAddress.m
- Mobile Buy SDK/Mobile Buy SDK/Models/BUYCheckout.m
- Mobile Buy SDK/Mobile Buy SDK/Models/BUYCollection.m
- Mobile Buy SDK/Mobile Buy SDK/Models/BUYProduct.m
- Mobile Buy SDK/Mobile Buy SDK/Utils/NSDictionary+Additions.h
- Mobile Buy SDK/Mobile Buy SDK/Utils/NSDictionary+Additions.m
Protects from crashing when sending message to NSNull property by converting to nil
@runmad
> Add NSNull checks and convert to nil

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/CheckoutViewController.m
This adds viewing the status page for an order after a completed checkout.
> Add status page to Advanced Sample App demo

- Mobile Buy SDK/Mobile Buy SDK/Utils/BUYProduct+Options.m
This adds additional logic to the method that determines whether a product has a single, default variant.
> Improved check for default variant

- Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayHelpers.m
> Fix deprecated property usage for Apple Pay

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/Info.plist
- Mobile Buy SDK Sample Apps/Sample App Swift/Mobile Buy SDK Swift Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Sample App Swift/Mobile Buy SDK Swift Sample/Info.plist
- Mobile Buy SDK Sample Apps/Sample App Web/Mobile Buy SDK Web Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Sample App Web/Mobile Buy SDK Web Sample/Info.plist
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m
- Mobile Buy SDK/Mobile Buy SDK/Info.plist
- Mobile-Buy-SDK.podspec
`1.2.1` -> `1.2.2` version updates
> 1.2.2 version updates

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/Info.plist
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m
- Mobile Buy SDK/Mobile Buy SDK/Info.plist
- Mobile-Buy-SDK.podspec
Adds the requires release version updates.
> 1.2.3 release version

- README.md
This adds sections links in the top of the README. I've also included a new Help section with a link to our forum.
> Add help section + section links to readme

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m
- Mobile Buy SDK/Mobile Buy SDK/Info.plist
> Adds bundle identifier to user_agent

- Mobile Buy SDK/Mobile Buy SDK/Models/BUYLineItem.m
- Mobile Buy SDK/Mobile Buy SDK/Product View/BUYProductViewController.m
- Mobile-Buy-SDK.podspec
BUYLineItem didn't have a productId when initialized with BUYVariant
> BUYLineItem didn't have a productId when initialized with BUYVariant

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYErrorTests.m
- Mobile Buy SDK/Mobile Buy SDK Tests/BUYOptionValueTests.m
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- adds `BUYError` tests
- adds `BUYOptionValue` tests
> Add a few model tests

- Mobile Buy SDK/Mobile Buy SDK Tests/test_shop_data.json
This reverts a file which was accidentally committed with conflicting changes after a merge, even though it was only supposed to be changed locally.
@davidmuzi
> Fix broken file after merge.

- Mobile Buy SDK Sample Apps/Sample App Customers/README.md
We'll need a readme file for the customer sample app. This adds one.
> Add Customer Sample App README.md

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
This updates the project file with changes automatically applied by Xcode in response to adding a new file to the project (on another branch). Not clear where these duplicates came from, but probably a merge gone wrong.
@davidmuzi @dbart01
> Xcode found redundant file references.

- Mobile Buy SDK Sample Apps/Sample App Swift/Mobile Buy SDK Swift Sample/ViewController.swift
Update the Swift Sample App.
Swift Sample did not compile after 2.0 SDK API and design chagnes. Partial fix for #176 
Update to simplify some API and use a model manager, as prescribed.
@dbart01 @davidmuzi
> Fixes for Swift Sample app

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Scripts/build_universal.sh
- updates universal aggregate target to build dynamic target with static flag
- organizes scheme order to match the target order
- refactors the universal build script
Fixes #178 
> Remove Buy Static target.

- Mobile Buy SDK Sample Apps/Sample App Customers/Sample App Customers/AccountViewController.swift
- Mobile Buy SDK Sample Apps/Sample App Customers/Sample App Customers/OrdersViewController.swift
Patches the customer sample app with new API changes.
> Adjust sample app to support API changes in the SDK.

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/ProductListViewController.m
Models require a model manager when initialized.
@dbart01
> Update to new API for checkout creation

- Mobile Buy SDK/Mobile Buy SDK/Utils/BUYApplePayAuthorizationDelegate.m
Removes polling in `BUYApplePayAuthorizationDelegate`, a change that was somehow lost somewhere at some point during a merge...
@bgulanowski @gabrieloc
> Remove left over polling in BUYApplePayAuthorizationDelegate.

- Mobile Buy SDK Sample Apps/Sample App Advanced/PRODUCT_VIEW_README.md
- Mobile Buy SDK Sample Apps/Sample App Advanced/README.md
- README.md
Change README files for SDK 2.0. Basically just changes in naming and API.
README files were out of date.
@dbart01 @gabrieloc
> Update README files

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYRequestOperationTests.m
- Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCustomer.m
Fix two issues with the model.
1. incorrect delete rules on the Order - LineItem relationship.
2. incorrect property synthesis for a dynamic property defined in Core Data model. (This only affects builds that use the core data build option)
@dbart01
> Two model-level fixes

- Mobile Buy SDK/Mobile Buy SDK/Models/Mobile Buy SDK.xcdatamodeld/Mobile Buy SDK.xcdatamodel/contents
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYCustomer.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/_BUYCustomer.m
Fix: #256 
defaultAddres->defaultAddress
@bgulanowski
> Fix type for defaultAddress on Customer

- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/Product View/ProductViewController.m
- Mobile Buy SDK Sample Apps/Sample App Advanced/Mobile Buy SDK Advanced Sample/ProductListViewController.m
- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+StorefrontTests.m
- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClientTest.m
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Routing.h
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Routing.m
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
This PR introduces API to fetch the tags for all products, as well as an API to fetch products filtered by tags.
@bgulanowski @sav007
> Product tags support

- README.md
Fixes https://github.com/Shopify/mobile-buy-sdk-ios/issues/295
@davidmuzi @gabrieloc
> Update snippet in README to use correct callback arguments.

- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYCart.m
- Mobile Buy SDK/Mobile Buy SDK/Models/Transient/BUYCheckout.m
Add some required casting
@bgulanowski
> Xcode 8 Support

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m
Adds a unit test for customer creation
@bgulanowski @krisorr
> Customer creation tests

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m
Fixes a failing test by updated test credentials 
@bgulanowski
> Fix testCustomerInvalidEmailPassword

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
Xcode issues a warning about the search paths setting, so updated to match recommended setting.
@gabrieloc
> Use recommended setting from Xcode.

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+StorefrontTests.m
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
Fix incorrect parameter for filtering products by tag.
Also update test.
Fixes #323 
@davidmuzi
> Use correct parameter name tags->tag.

- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h
Make the comments for Default sort order clearer
@bgulanowski
> Make the sort ordering comment clearer

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/README.md
- README.md
> Fix links for sample apps

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/ActionableFooterView.h
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Product View/ActionableFooterView.m
Left over from the updates for 2.0.
@davidmuzi @gabrieloc
> Remove code from sample app that is not used

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
See title
Fixes #333 
@davidmuzi @gabrieloc
> Add SDK as embedded bundle.

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+CustomerTests.m
Cherry picked from #338 - we only need the one change here.
Also #348 
Note this is targeting the release/2.0.1 branch, which is also being readied for merge into master and release.
@davidmuzi @gabrieloc @krisorr
> Fixes cherry picked from develop

- README.md
> Update method signatures in readme

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYClient+StorefrontTests.m
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.m
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.h
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient.m
Allows a custom page size to be set based off the type of data being fetched
@bgulanowski @davidmuzi @krisorr
> Product, Collection, and Tag-specific page sizes

- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/AccountViewController.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/ActionCell.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/AppDelegate.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/AuthenticationDelegate.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/BUYClient+Extensions.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/LineItemCell.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/LoginViewController.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/OrdersViewController.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers/SignupViewController.swift
Updates the Customer sample app to use Swift 3
@bgulanowski @dbart01
> Convert Customer app to use Swift 3

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYPaymentProviderTests.m
- Mobile Buy SDK/Mobile Buy SDK/Payment Providers/BUYApplePayPaymentProvider.m
Updates checkout after Apple Pay payment is authorized
Resolves #362 
> Update checkout after authorizing Apple Pay payment

- Mobile Buy SDK/Mobile Buy SDK Tests/BUYOptionValueTests.m
- Mobile Buy SDK/Mobile Buy SDK Tests/BUYProductTests.m
- Mobile Buy SDK/Mobile Buy SDK Tests/BUYProductVariantTests.m
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYOptionValue.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYOptionValue.m
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProduct.m
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProductVariant.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYProductVariant.m
Update the default variant check to match Android and server side
Resolves #367
> Update default variant check

- README.md
> [#379] Fix broken links in README

- Mobile Buy SDK/CHANGELOG.md
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
Add CHANGELOG to project to show version changes
Resolves #401 
@davidmuzi @bgulanowski @gabrieloc @dbart01
> [#401] Add CHANGELOG to project

- Mobile Buy SDK/CHANGELOG.md
- Mobile Buy SDK/Mobile Buy SDK/Data/BUYClient+Storefront.h
> [#403] Add missing parameter docs for collection callback block

- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample App.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample App.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/AppDelegate.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Back.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Front.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Large.imagestack/Middle.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Back.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Front.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - Small.imagestack/Middle.imagestacklayer/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Assets.xcassets/LaunchImage.launchimage/Contents.json
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/BUYClient+Extensions.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Base.lproj/Main.storyboard
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Info.plist
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/ViewController.swift
Create a tvOS project that will be used for the tvOS sample app
Resolves #409 
> [#409] Create a tvOS project

- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample App.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Collections.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/DataProvider.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Products.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/ViewController.swift
Created collection and product objects to abstract model object away from view controller.
Also removed the DataProviderDelegate and added completion blocks to DataProvider functions.
`Products` object will be used when container cell is configured with the horizontal products collection view
Resolves #422 
> [#422] Created collection and product objects

- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample App.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/AsyncImageView.h
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/AsyncImageView.m
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Base.lproj/Main.storyboard
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/DataProvider.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample App-Bridging-Header.h
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/ProductCollectionViewCell.swift
- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/Mobile Buy SDK tvOS Sample/ProductsViewModel.swift
Configuration of product cells to show product image, title and price.
Product image uses AsyncImageView (imported in Objective-C and uses bridging header) in order to assign image view with BUYLink right from the ProductsViewModel.
Resolves #414 
> [#414] Configure product cells

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Assets.xcassets/Complication.complicationset/Circular.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Assets.xcassets/Complication.complicationset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Assets.xcassets/Complication.complicationset/Extra Large.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Assets.xcassets/Complication.complicationset/Modular.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Assets.xcassets/Complication.complicationset/Utilitarian.imageset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ExtensionDelegate.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/Info.plist
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/InterfaceController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/NotificationController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/PushNotificationPayload.apns
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App/Assets.xcassets/AppIcon.appiconset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App/Base.lproj/Interface.storyboard
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App/Info.plist
Create a watchOS extension (Swift) on the Advanced Sample App
Resolves #437
> [#437] Create watchOS extension

- Mobile Buy SDK Sample Apps/Mobile Buy SDK tvOS Sample/README.md
Add README.md for tvOS to explain each class and how to use the sample app.
Resolves #450
> [#450] Add README.md for tvOS

- Scripts/run_tests.sh
> Write test json in CI script

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/DataProvider.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ExtensionDelegate.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/InterfaceController.swift
- Mobile Buy SDK Sample Apps/Customers App - Swift/Sample App Customers.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Buy.h
The data provider will be the only entity dealing with the Mobile Buy SDK in terms of network calls. It will download products and will hand those results over to controllers when requested.
Resolves #461
> [#461] Data Provider for watchOS Sample App

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample.xcodeproj/project.pbxproj
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/BaseModel.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/DataProvider.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ExtensionDelegate.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/InterfaceController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductRowController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductsModel.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App/Base.lproj/Interface.storyboard
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/project.pbxproj
- Mobile Buy SDK/Mobile Buy SDK/Buy.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYImageLink.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Persistent/BUYImageLink.m
Created a products model to download products for the collection products controller. This class allows us to abstract model objects from the interface controller.
Resolves #464
> [#464] Products Model

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/InterfaceController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductDetailsInterfaceController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductItem.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductsModel.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App/Base.lproj/Interface.storyboard
Added a `WKInterfacePicker` to select variants on the product details interface controller. Only appears if the product has one option. For products with more than one option, they'll have to use their iPhone to view and buy the product.
Resolves #468
> [#468] Product Details Variant Picker

- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/AppDelegate.m
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/CollectionListViewController.m
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Images.xcassets/AppIcon.appiconset/Contents.json
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/Info.plist
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/ProductListViewController.h
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK Advanced Sample/ProductListViewController.m
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/InterfaceController.swift
- Mobile Buy SDK Sample Apps/Advanced App - ObjC/Mobile Buy SDK watchOS Sample App Extension/ProductsModel.swift
Add handoff capabilities to the product details controller so that the iOS app opens up the `ProductViewController`
Resolves #459
> [#459] Add handoff capabilities

- Buy/Buy.h
- Buy/Custom/GraphQL+ScalarSupport.swift
- Buy/Global.swift
- Buy/GraphClient.swift
- Buy/GraphError.swift
- Buy/GraphResult.swift
- BuyTests/BuyTests.swift
Updates file headers with appropriate license and copyright.
> File headers

- Buy.xcodeproj/project.pbxproj
- Buy/Generated/ApiSchema/Customer.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressCreateInput.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressCreatePayload.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressDeleteInput.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressDeletePayload.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressUpdateInput.swift
- Buy/Generated/ApiSchema/CustomerMailingAddressUpdatePayload.swift
- Buy/Generated/ApiSchema/MailingAddress.swift
- Buy/Generated/ApiSchema/MailingAddressConnection.swift
- Buy/Generated/ApiSchema/MailingAddressEdge.swift
- Buy/Generated/ApiSchema/MailingAddressInput.swift
- Buy/Generated/ApiSchema/Mutation.swift
- Buy/Generated/ApiSchema/Node.swift
- Buy/Generated/ApiSchema/Order.swift
- Buy/Generated/ApiSchema/PurchaseSession.swift
- Buy/Generated/ApiSchema/PurchaseSessionCreateInput.swift
- Buy/Generated/ApiSchema/PurchaseSessionUpdateInput.swift
- Buy/Generated/ApiSchema/Shop.swift
These changes are the result of automatic schema generation - byproduct of running `update_schema`. 
It includes changes from this PR: https://github.com/Shopify/shopify/pull/98111
> Schema update

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/CollectionCell.xib
- Sample Apps/Storefront/Storefront/DepressibleCell.swift
- Sample Apps/Storefront/Storefront/ProductCell.swift
Adds a simple tap animation when a collection cell is selected. It is a subclass of `UICollectionViewCell` so it's easily reused in any other subclass.
> Cell selection

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CollectionCell.swift
- Sample Apps/Storefront/Storefront/CollectionCell.xib
- Sample Apps/Storefront/Storefront/Currency.swift
- Sample Apps/Storefront/Storefront/DepressibleCell.swift
- Sample Apps/Storefront/Storefront/Fragment+ProductConnectionQuery.swift
- Sample Apps/Storefront/Storefront/ProductCell.xib
- Sample Apps/Storefront/Storefront/ProductViewModel.swift
- Sample Apps/Storefront/Storefront/ProductsViewController.swift
- Sample Apps/Storefront/Storefront/VariantViewModel.swift
- adds currency formatter
- adds `VariantViewModel` as a child of `ProductViewModel`, used for calculating the minimum price for products
- adds titles and prices to product cells in the products grid
> Product titles

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/ParallaxViewController.swift
Adds a `ParallaxViewController`, which is a UI component that automatically manages touch events via a proxy for two overlapping views: a `UIScrollView` and an arbitrary `UIView` header view. The parallax controller also manages the layout of the header view to create a parallax effect when moving the scroll view.
> The ParallaxViewController

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/Fragment+ImageConnectionQuery.swift
- Sample Apps/Storefront/Storefront/Fragment+ProductConnectionQuery.swift
- Sample Apps/Storefront/Storefront/ImageViewModel.swift
- Sample Apps/Storefront/Storefront/ProductCell.swift
- Sample Apps/Storefront/Storefront/ProductDetailsViewController.swift
- Sample Apps/Storefront/Storefront/ProductsViewController.swift
Adds a simple, incomplete product details implementation using `ImageViewController` to show a paging image collection that can be panned horizontally. Also adds various model and view model classes to support the above.
> Implement products details.

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CartButton.swift
- Sample Apps/Storefront/Storefront/CollectionCell.swift
- Sample Apps/Storefront/Storefront/CollectionsViewController.swift
- Sample Apps/Storefront/Storefront/HTMLParser.swift
- Sample Apps/Storefront/Storefront/ProductHeaderCell.xib
- Sample Apps/Storefront/Storefront/ProductsViewController.swift
- Sample Apps/Storefront/Storefront/RoundedButton.swift
Introduces a few button subclasses to abstract styling of a few components:
- `RoundedButton` provides rounded corners for any button
- `CartButton` provides `Add to Cart` subtitle for all titles set on it
Hooks up product selection from hybrid collection view.
> Product details refinement.

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/ProductHeaderCell.xib
- Sample Apps/Storefront/Storefront/SeparatorView.swift
Separators are important. This introduces a `UIView` subclass that automatically resizes and positions itself in it's superview according to the specified `Position` making it easy to add `UITableViewCell`-style 1px separators to in view.
> Separators

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CartCell.xib
- Sample Apps/Storefront/Storefront/CartController.swift
- Sample Apps/Storefront/Storefront/CartViewController.swift
- Sample Apps/Storefront/Storefront/Fragment+VariantConnectionQuery.swift
- Sample Apps/Storefront/Storefront/ProductCell.xib
- Sample Apps/Storefront/Storefront/ProductsViewController.swift
- Sample Apps/Storefront/Storefront/TotalsViewController.swift
Previously we introduced the cart. The UI layout and architecture was less than ideal so here, we modify the structure to use view controller containment and `ParallaxViewController` to provide a better look UI and a smoother user experience.
> Cart (season 2)

- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CartButton.swift
- Sample Apps/Storefront/Storefront/CollectionsViewController.swift
- Sample Apps/Storefront/Storefront/ProductsViewController.swift
Adds the cart button to all relevant screens.
> Cart button everywhere

- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CartButton.swift
- Sample Apps/Storefront/Storefront/CollectionCell.xib
There are many edge cases and behaviours that affect how the cart button displays badge animations. It took some refinement to make it perfect in all cases.
> Refine cart button

- Sample Apps/Storefront/Storefront/UIImageView+Remote.swift
Add a simple in-memory cache for fetching images via the network. Doing so greatly improves appearance of images when paginating products / collections and reloading table / collection cells that contain images.
> Image cache

- Mobile Buy SDK/Mobile Buy SDK/Models/Transient/BUYCheckout.h
- Mobile Buy SDK/Mobile Buy SDK/Models/Transient/BUYCheckout.m
`BUYCheckout.lineItemsArray` should be array of `BUYLineItem` instead of `BUYCartLineItem`
> Typo in `BUYCheckout. lineItemsArray` 

- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Buy.xcscheme
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Mobile Buy SDK Tests.xcscheme
- Mobile Buy SDK/Mobile Buy SDK.xcodeproj/xcshareddata/xcschemes/Static Universal Framework.xcscheme
Xcode automated scheme changes.
> Xcode version update

- Buy.xcodeproj/project.pbxproj
- Buy.xcodeproj/xcshareddata/xcschemes/Pay.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/PayTests.xcscheme
Share the `Pay` target scheme, minor project adjustments.
> Pay schemes

- Buy.xcodeproj/project.pbxproj
- Pay/PayCheckout.swift
- Pay/PayDiscount.swift
- PayTests/Models.swift
- PayTests/PayCheckoutTests.swift
- PayTests/PayDiscountTests.swift
- PayTests/PayLineItemTests.swift
- PayTests/PaySessionTests.swift
Adds tests for `PayDiscount`, `PayCheckout` and `PayLineItem`. Move model creation into `Models` file to share across all tests.
> Pay discount, checkout, line item tests

- Buy.xcodeproj/project.pbxproj
- Pay/PassKit+SummaryItems.swift
- Pay/PayAddress.swift
- Pay/PayShippingRate.swift
- PayTests/Models.swift
- PayTests/PassKit+SummaryItemTests.swift
- PayTests/PayAddressTests.swift
- PayTests/PayAuthorizationTests.swift
- PayTests/PayCheckoutTests.swift
- PayTests/PayCurrencyTests.swift
- PayTests/PayShippingRateTests.swift
Adds tests for:
- `PayCurrency`
- `PayAddress`
- `PayShippingRate`
- `PayAuthorization`
- PassKit additions
> Pay missing tests

- Buy.xcodeproj/project.pbxproj
- Buy/Card.Client.swift
- Buy/Card.CreditCard.swift
- Buy/Card.swift
- Buy/Graph.Client.swift
- BuyTests/Card.ClientTests.swift
- BuyTests/Card.CreditCardTests.swift
It's like pole vaulting but with credit cards.
Adds support for card vaulting. Introduces a few new classes to make this happen:
- The `Card.Client` is like `Graph.Client` but only for card server
- The `Card.CreditCard` model encapsulates all credit card data and provides an internal dictionary serialization implementation
- Tests with 100% coverage for all the above
> Card vaulting

- Sample Apps/Storefront/Storefront/Client.swift
Migrate `Graph.Task` -> `Task`.
> Migrate `Graph.Task`

- README.md
Adds cache documentation. 
cc: @sav007
> Cache docs

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/CartViewController.swift
- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/Color.swift
- Sample Apps/Storefront/Storefront/TotalsViewController.swift
Adds proper payment buttons to the cart view.
> Payment buttons

- README.md
- Adds `task.resume()` in snippets
- Fixes links
Fixes #610
> Readme refinements

- README.md
Documents how search is exposed through the `query` parameter. Directly related to the search syntax on [Shopify](https://github.com/Shopify/shopify/wiki/Search-Syntax).
Ready for content review: @rorytanner 
Please look over to make sure I didn't miss anything: @sav007
> Search documentation

- Buy.xcodeproj/project.pbxproj
- Buy/Generated/Storefront/Article.swift
- Buy/Generated/Storefront/ArticleAuthor.swift
- Buy/Generated/Storefront/ArticleConnection.swift
- Buy/Generated/Storefront/ArticleEdge.swift
- Buy/Generated/Storefront/ArticleSortKeys.swift
- Buy/Generated/Storefront/Blog.swift
- Buy/Generated/Storefront/BlogConnection.swift
- Buy/Generated/Storefront/BlogEdge.swift
- Buy/Generated/Storefront/BlogSortKeys.swift
- Buy/Generated/Storefront/Comment.swift
- Buy/Generated/Storefront/CommentAuthor.swift
- Buy/Generated/Storefront/CommentConnection.swift
- Buy/Generated/Storefront/CommentEdge.swift
- Buy/Generated/Storefront/CurrencyCode.swift
- Buy/Generated/Storefront/Node.swift
- Buy/Generated/Storefront/Shop.swift
- adds Blog model and supporting connection / edges
- adds Article model and supporting connection / edges
- adds Comment model and supporting connection / edges
- adds support for building a blog
cc: @sav007
> Update schema (auto-generated).

- Sample Apps/Storefront/README.md
Updates the sample app with instruction on how to get it up and running.
Please review the content: @rorytanner 
Please copy to Android sample app: @sav007
> Update sample app readme

- README.md
Update the README instructions and fix indentation.
Fixes #609 
Fixes #624
> Update dynamic framework installation instructions.

- Sample Apps/Storefront/Storefront/Client.swift
Expose credentials to the GraphQL test shop for easily demoing the sample application functionality.
We should do same for Android @sav007 
cc: @minasmart
> Share credentials

- Buy/Buy.h
- Mobile-Buy-SDK.podspec
- README.md
Adds support for CocoaPods by introducing a `.podspec`. We need to conditionally import `md5.h` to CocoaPods' build system.
Fixes #633
> CocoaPods support

- .travis.yml
- Sample Apps/Storefront/Storefront.xcodeproj/xcshareddata/xcschemes/Storefront.xcscheme
- Scripts/test_sample
Adds configuration to TravisCI to build the sample application and ensure the build succeeds. No actual testing is performed since the sample app doesn't have a unit test bundle. It is simply to verify the application still builds correctly.
Fixes #262 
Might want to consider doing something similar on Android.
cc: @sav007
> Sample app on CI.

- README.md
We've had some inquiries about how to integrate customer accounts with SDK 3.0. To provide more guidance I've added documentation for all essential customer-related functionality.
We should copy over to Android after content fixes: @sav007
> Customer docs

- .travis.yml
Adds Slack notifications for `failing` and `failed before but now succeeds` states. Slack channel is provided via `secure` parameter and is encrypted.
> Travis CI notifications

- Buy/Generated/Storefront/MailingAddress.swift
Automated schema update for `MailingAddress` nullability.
> MailingAddress nullability.

- README.md
Updates CocoaPods install instructions.
> Update CocoaPods install instructions.

- Buy/Generated/Storefront/ProductVariant.swift
- Buy/Generated/Storefront/Shop.swift
Fix documentation comments with deprecation attributes.
Fixes #693
> Fix documentation comments with deprecation attributes.

- README.md
- Sample Apps/Storefront/README.md
Update readme with additional step to update git submodules
> Update sample readme

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/Storefront.entitlements
The bundle identifier has been changed and added entitlements for Apple Pay to facilitate better testing of the payments implementation.
> Configure entitlements and bundle identifier for Apple Pay.

- Mobile-Buy-SDK.podspec
Updates the `.podspec` with support for `watchOS` and `tvOS`.
> Support for multi-platform cocoapods.

- README.md
Update the code snippets to use `Input<T>` and adds a case study example showcasing where it's necessary in customer updates.
> Readme Input<T> documentation

- Sample Apps/Storefront/Storefront/CartViewController.swift
- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/ClientQuery.swift
Demonstrates how to use the discount code mutation to apply a user-provided discount to a checkout.
> Add discount code support in Sample App

- Buy/Client/Graph.Cache.swift
- Buy/Client/Graph.Client.swift
- BuyTests/Client/Graph.CacheTests.swift
- BuyTests/Client/Graph.TaskTests.swift
Creates shop-based directory structure for the cache layer to allow multiple clients with different shop domains to co-exist within a single application sandbox. Adds and updates tests to verify the above.
> Shop-separated cache

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/CartViewController.swift
- Sample Apps/Storefront/Storefront/CheckoutViewModel.swift
- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/ClientQuery.swift
- Sample Apps/Storefront/Storefront/Fragment+CheckoutQuery.swift
- Sample Apps/Storefront/Storefront/GiftCardViewModel+PayGiftCard.swift
- Sample Apps/Storefront/Storefront/GiftCardViewModel.swift
Add support for gift cards in the sample app.
> Sample app gift cards

- .travis.yml
Separates a single TravisCI build into parallel jobs.
| Jobs |
| - |
| ![screen shot 2018-08-15 at 1 31 47 pm](https://user-images.githubusercontent.com/5244861/44162900-b0b1a600-a08f-11e8-8b6d-dc470510237d.png) |
> Separate CI build into jobs.

- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront/AccountController.swift
- Sample Apps/Storefront/Storefront/Base.lproj/Main.storyboard
- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/ClientQuery.swift
- Sample Apps/Storefront/Storefront/CollectionsViewController.swift
- Sample Apps/Storefront/Storefront/CustomerCoordinator.swift
- Sample Apps/Storefront/Storefront/CustomerViewController.swift
- Sample Apps/Storefront/Storefront/CustomerViewModel.swift
- Sample Apps/Storefront/Storefront/Fragment+OrderConnectionQuery.swift
- Sample Apps/Storefront/Storefront/Fragment+OrderLineItemConnectionQuery.swift
- Sample Apps/Storefront/Storefront/LoginViewController.swift
- Sample Apps/Storefront/Storefront/OrderCell.swift
- Sample Apps/Storefront/Storefront/OrderCell.xib
- Sample Apps/Storefront/Storefront/OrderViewModel.swift
- Sample Apps/Storefront/Storefront/OrdersViewController.swift
- Sample Apps/Storefront/Storefront/ProfileViewController.swift
- Sample Apps/Storefront/Storefront/SeparatorView.swift
Adds support customer login, account overview and order list in the sample app.
> User accounts

- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/ClientQuery.swift
Use non-deprecated gift card application mutation.
> Use non-deprecated gift card application mutation.

- Buy/Generated/Storefront.swift
- Buy/Generated/Storefront/ArticleSortKeys.swift
- Buy/Generated/Storefront/BlogSortKeys.swift
- Buy/Generated/Storefront/Checkout.swift
- Buy/Generated/Storefront/CollectionSortKeys.swift
- Buy/Generated/Storefront/CountryCode.swift
- Buy/Generated/Storefront/CurrencyCode.swift
- Buy/Generated/Storefront/CustomerActivateInput.swift
- Buy/Generated/Storefront/OrderSortKeys.swift
- Buy/Generated/Storefront/ProductCollectionSortKeys.swift
- Buy/Generated/Storefront/ProductImageSortKeys.swift
- Buy/Generated/Storefront/ProductSortKeys.swift
- Buy/Generated/Storefront/ProductVariantSortKeys.swift
- Buy/Generated/Storefront/WeightUnit.swift
Bump Swift Gen submodule, update schema docs.
> Bump swift gen submodule, update schema docs.

- Buy.xcodeproj/project.pbxproj
- Buy/Generated/Storefront/Blog.swift
- Buy/Generated/Storefront/CheckoutAttributesUpdateV2Input.swift
- Buy/Generated/Storefront/CheckoutAttributesUpdateV2Payload.swift
- Buy/Generated/Storefront/CustomerResetByUrlPayload.swift
- Buy/Generated/Storefront/Mutation.swift
- Buy/Generated/Storefront/Order.swift
- Buy/Generated/Storefront/QueryRoot.swift
- Buy/Generated/Storefront/Shop.swift
- Adds support for fetching articles by handle
- Adds support for improved checkout attributes
- Adds access token field to the customer reset mutation payload
- Adds support for reseting customer by URL via universal links
- Adds `name` field on `Storefront.Order`
- Adds improved support for blogs and articles
cc: @sav007
> Update schema (auto-generated)

- Buy/Generated/Storefront/MoneyInput.swift
- Buy/Generated/Storefront/MoneyV2.swift
- Scripts/update_schema
Update `MoneyV2.amount` to use `Decimal` instead of `String`.
> MoneyV2 enhancement

- Buy/Generated/Storefront/CustomerActivatePayload.swift
- Buy/Generated/Storefront/CustomerAddressCreatePayload.swift
- Buy/Generated/Storefront/CustomerAddressDeletePayload.swift
- Buy/Generated/Storefront/CustomerAddressUpdatePayload.swift
- Buy/Generated/Storefront/CustomerDefaultAddressUpdatePayload.swift
- Buy/Generated/Storefront/CustomerErrorCode.swift
- Buy/Generated/Storefront/CustomerRecoverPayload.swift
- Buy/Generated/Storefront/CustomerResetByUrlPayload.swift
- Buy/Generated/Storefront/CustomerResetPayload.swift
Add support for customer user errors fields in various models.
> Customer user error

- Buy.xcodeproj/project.pbxproj
- Buy/Generated/Storefront/CheckoutDiscountCodeApplyV2Payload.swift
- Buy/Generated/Storefront/CheckoutEmailUpdateV2Payload.swift
- Buy/Generated/Storefront/CheckoutShippingAddressUpdateV2Payload.swift
- Buy/Generated/Storefront/Mutation.swift
Adds support for checkout mutations, v2.
> Checkouts mutations

- BuyTests/Client/Graph.ClientTests.swift
- BuyTests/Client/Graph.TaskTests.swift
- Sample Apps/Storefront/Storefront/Client.swift
- Sample Apps/Storefront/Storefront/ClientQuery.swift
Updates deprecated mutations in sample app.
> Update deprecated mutations in sample app.

- Buy/Generated/Storefront/Customer.swift
- Buy/Generated/Storefront/Product.swift
- Buy/Generated/Storefront/Shop.swift
Update docs for permission-gated fields.
> Update doc comments

- .travis.yml
- Buy.xcodeproj/project.pbxproj
- Buy.xcodeproj/xcshareddata/xcschemes/Buy tvOS.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/Buy watchOS.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/Buy.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/BuyTests.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/Documentation.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/Pay.xcscheme
- Buy.xcodeproj/xcshareddata/xcschemes/PayTests.xcscheme
- Buy/Card/Card.Client.swift
- Buy/Card/Card.CreditCard.swift
- Buy/Client/Graph.Cache.swift
- Buy/Client/Graph.CacheItem.swift
- Buy/Client/Graph.QueryError.swift
- Buy/Client/Graph.RetryHandler.swift
- Buy/Client/Graph.Task.swift
- Buy/Custom/Optional+Input.swift
- BuyTests/Card/Card.ClientTests.swift
- BuyTests/Client/Graph.ClientTests.swift
- BuyTests/Client/Graph.TaskTests.swift
- Pay/PayLineItem.swift
- Sample Apps/Storefront/Storefront.xcodeproj/project.pbxproj
- Sample Apps/Storefront/Storefront.xcodeproj/xcshareddata/xcschemes/Storefront.xcscheme
- Sample Apps/Storefront/Storefront/CartController.swift
- Upgrades CI to Xcode 10.2
- Migrates all targets to Swift 5
- Project file optimization recommended for Xcode 10.2
> Update to Xcode 10.2

- README.md
changed checkoutCompleteWithCreditCard to checkoutCompleteWithCreditCardV2
fixes #1023
> updated doc for credit card v2

- .travis.yml
- Scripts/setup_simulator
Update CI to Xcode 11 and iOS 13.
> Xcode 11 and iOS 13

- README.md
Adds a docs link for 3d secure to the readme
> Add 3d secure to readme

- Buy/Generated/Storefront/AppliedGiftCard.swift
- Buy/Generated/Storefront/Article.swift
- Buy/Generated/Storefront/ArticleAuthor.swift
- Buy/Generated/Storefront/ArticleSortKeys.swift
- Buy/Generated/Storefront/Blog.swift
- Buy/Generated/Storefront/BlogSortKeys.swift
- Buy/Generated/Storefront/Checkout.swift
- Buy/Generated/Storefront/CheckoutLineItemUpdateInput.swift
- Buy/Generated/Storefront/CheckoutLineItemsRemovePayload.swift
- Buy/Generated/Storefront/CollectionSortKeys.swift
- Buy/Generated/Storefront/Comment.swift
- Buy/Generated/Storefront/CommentAuthor.swift
- Buy/Generated/Storefront/CreditCard.swift
- Buy/Generated/Storefront/CropRegion.swift
- Buy/Generated/Storefront/CustomerCreateInput.swift
- Buy/Generated/Storefront/CustomerResetInput.swift
- Buy/Generated/Storefront/ImageContentType.swift
- Buy/Generated/Storefront/Mutation.swift
- Buy/Generated/Storefront/OrderSortKeys.swift
- Buy/Generated/Storefront/PageSortKeys.swift
- Buy/Generated/Storefront/Product.swift
- Buy/Generated/Storefront/ProductCollectionSortKeys.swift
- Buy/Generated/Storefront/ProductImageSortKeys.swift
- Buy/Generated/Storefront/ProductSortKeys.swift
- Buy/Generated/Storefront/ProductVariantSortKeys.swift
- Buy/Generated/Storefront/QueryRoot.swift
- Buy/Generated/Storefront/TokenizedPaymentInputV2.swift
Updates documentation on fields and mutations
Changes that are not documentation changes.
> API 2020-01 Documentation Update

- Gemfile
- Gemfile.lock
- Scripts/build
Refactors the script to not assume the location it's being run from. 
Changes gemfile to use git instead of submodules. 
<# Describe your changes #>
Fixes <# issue number #>
> Refactored build plus gemfile

- .github/workflows/build.yml
We need to keep this spreadsheet up-to-date for now, so let's make sure maintainers know to update it.
> Add version spreadsheet to release steps

- README.md
Updates the README to include payment processing request form for native mobile apps and sales channels.
> Update README.md to include payment processing form

- Scripts/increment_version
This is a small update to the `increment_version` script that also handles updating the `.podspec`.
> Increment Podspec Version Automatically

- Mobile-Buy-SDK.podspec
Updates the platform attributes to match Xcode and `Package.swift`.
> Fix Podspec Platform Versions
